version: "3"

x-postgres-variables: &postgres-variables
  POSTGRES_USER: media_match
  # TODO: Use a secret instead.
  POSTGRES_PASSWORD: hunter2
  POSTGRESS_HOST: db
  POSTGRESS_DBNAME: media_match

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      ENV_CONFIG: "true"
      PRODUCTION: "false"
      ROLE_HASHER: "true"
      ROLE_MATCHER: "true"
      ROLE_CURATOR: "true"
      <<: *postgres-variables
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
        - ./.devcontainer/pg-scripts/init-multiple-pg-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-pg-dbs.sh
        - postgres-data:/var/lib/postgresql/data
    environment:
      <<: *postgres-variables
      POSTGRES_MULTIPLE_DATABASES: media_match
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge
